### ISSUE TITLE
Add docs for `onCreation` callback

### ISSUE THREAD

**Issue by better-salmon** [caching-tools/next-shared-cache#101]
Create docs for `dev`, `serverDistDir` parameters.

```js
IncrementalCache.onCreation(({ dev, serverDistDir }) => {
  return {
    //
  };
});
```

**Comment by pavelee** [comment]
Hey, do you need a help with this one?

I am currently looking into the package, so I could try document it

**Comment by better-salmon** [comment]
Hey @pavelee, thanks for your attention to my project. You can fork the project and submit a pull request. It would be so helpful.
