### ISSUE TITLE
Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by AlexisWalravens** [caching-tools/next-shared-cache#112]
**Describe the bug**
I followed and copied exactly the example here: https://github.com/caching-tools/next-shared-cache/blob/canary/docs/examples/use-with-redis.md

I used the example with the normal redis (not stack).

And I get the following error:
```
Failed to update prerender cache for 44895796bd01128d010b1b73580f573032b5251b40c1999a9c0798af8e159942 TypeError: Cannot read properties of undefined (reading 'set')
    at _IncrementalCache.set (/Users/.../test-project/node_modules/.pnpm/@neshca+cache-handler@0.4.2/node_modules/@neshca/cache-handler/dist/cache-handler.js:258:35)
```

**To Reproduce**
I reproduced it by cloning the NextJS docs example described here:
[https://github.com/vercel/next.js/blob/canary/examples/cache-handler-redis/README.md](https://github.com/vercel/next.js/blob/canary/examples/cache-handler-redis/README.md)

1. `npx create-next-app --example cache-handler-redis cache-handler-redis-app`
2. Edit `next.config.js` with: 
```
incrementalCacheHandlerPath: require.resolve(
      "./cache-handler-redis.js" // if you're using Redis without JSON support
      // "./cache-handler-redis-stack.js"
    ),
```
3. Run `npm run dev`
4. Go to http://localhost:3000/WET
5. See error in logs

**Expected behavior**
Cache in redis without the error.

**Desktop (please complete the following information):**
 - OS: MacOS 14.1
 - Browser: Arc Version 1.15.2
 - Version
   - "@neshca/cache-handler": "latest",
   - "@neshca/json-replacer-reviver": "latest",

**Comment by better-salmon** [comment]
Hey, @AlexisWalravens! Thank you for this issue. I fixed the bug and published a new release. Update the dependency and ensure you are using [0.4.3](https://www.npmjs.com/package/@neshca/cache-handler/v/0.4.3) version

**Comment by AlexisWalravens** [comment]
Thanks @better-salmon it works great now!

Glad you did this helper, because I stumbled upon the new self-hosted docs PR last week and I tried to implement the custom cache handler myself with redis, and your solution is way elegant than mine. :)

**Comment by better-salmon** [comment]
Thank you too! Check out this docs section about [caching in dev mode](https://github.com/caching-tools/next-shared-cache/blob/canary/docs/examples/use-with-redis.md#development-environment). Also, I recommend avoiding the use of Redis in a development environment. Instead, using the built-in LRU cache or a Map as an alternative to Redis is best. You can opt-in to the local LRU cache if you do not call `onCreation`.

I plan to create documentation to explain this behavior in more detail.

In addition, please feel free to provide feedback and suggestions regarding the API, DX, and the usefulness of existing examples and documentation in the discussion's [ideas](https://github.com/caching-tools/next-shared-cache/discussions/categories/ideas) section.
