### ISSUE TITLE
Add example for `ioredis` package

### ISSUE THREAD

**Issue by better-salmon** [caching-tools/next-shared-cache#208]
The [`ioredis`](https://www.npmjs.com/package/ioredis) package has a different API than [`redis`](https://www.npmjs.com/package/redis). A new page is needed to guide migration between these two packages.

**Comment by MauriceArikoglu** [comment]
I would not recommend to copy the description from two other lib's documentations. Leads to confusion if the library would change. 

Instead I would argue it's more effective for you and the users if we'd describe a schema for initializing, storing and retrieving data. Through a generic description, other storage solutions could become viable as well.

**Comment by better-salmon** [comment]
Look at the [Creating a Custom Handler](https://caching-tools.github.io/next-shared-cache/usage/creating-a-custom-handler) guide to learn how to build a handler for ioredis or any other Redis client.
