### ISSUE TITLE
App hangs when Redis server is not available even with a fallback Handler

### ISSUE THREAD

**Issue by better-salmon** [caching-tools/next-shared-cache#230]
### Discussed in https://github.com/caching-tools/next-shared-cache/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **ezeparziale** December 16, 2023</sup>
I'm using the Redis stack example, as outlined in the following documentation: [https://caching-tools.github.io/next-shared-cache/redis-stack](https://caching-tools.github.io/next-shared-cache/redis-stack)

I'm testing all the features, but when I shut down Redis to test the LRU Cache, my page crashes.

I thought that when Redis is not available, the LRU cache would work, but I can't test this scenario. Any idea?</div>

**Comment by zipme** [comment]
@better-salmon  I think this still happens:

```ts
 createRedisHandler({
      client,
      timeoutMs: 1000,
      keyExpirationStrategy: "EXAT",
    }),
```

Setting the `timeoutMs` here to 1000, if I stop the redis server the whole site hangs.
