### ISSUE TITLE
"Error: Socket already opened" running on production

### ISSUE THREAD

**Issue by jnm733** [caching-tools/next-shared-cache#284]
I'm using that example file handler that runs correctly on development, but when I run it on production with "next start" it let me the error: Error: Socket already opened

https://github.com/vercel/next.js/blob/canary/examples/cache-handler-redis/cache-handler.js 

Has it happened to you before? Do you know how I could solve it?

I'm using Next 14.1.0 with Redis 4.6.12

**Comment by better-salmon** [comment]
Hello @jnm733! If the Redis Node client can't connect to the Redis Server, it may throw a potentially misleading error (e.g., "Socket already opened"). Before building and starting your application, ensure your Redis Server runs and you pass the correct URL to the `createClient` function.

**Comment by MauriceArikoglu** [comment]
I am seeing `Socket closed unexpectedly` from time to time, after a successful start and connect

**Comment by better-salmon** [comment]
@MauriceArikoglu `Socket closed unexpectedly` is not a typical error. Please open a new issue if you could provide more information about it.

**Comment by MauriceArikoglu** [comment]
@better-salmon I will once I have more information. I suppose it could be due to a database configured timeout

**Comment by jnm733** [comment]
I'm deploying with Kubernetes and I have a route handler to use as healthcheck.

`import { NextRequest } from 'next/server';

export async function GET(request: NextRequest) {
  return Response.json({ ok: true });
}`

I have found that the connection error only appears if I use the K8s readiness and liveness probes.

Maybe the problem can come from the Route Handlers?

**Comment by victorfu** [comment]
> I'm using that example file handler that runs correctly on development, but when I run it on production with "next start" it let me the error: Error: Socket already opened
> 
> https://github.com/vercel/next.js/blob/canary/examples/cache-handler-redis/cache-handler.js
> 
> Has it happened to you before? Do you know how I could solve it?
> 
> I'm using Next 14.1.0 with Redis 4.6.12

+1

**Comment by gtjamesa** [comment]
I'm also seeing the same error with a Kubernetes deployment. I've wrapped my `client.connect()` call only to connect if the client is not open or ready, and this seems to have reduced the errors to about ~7 messages. The cache is working as intended, and it seems the errors now only happen at startup.

```js
// Skip Redis connection during builds
if (process.env.REDIS_AVAILABLE && buildId) {
  try {
    const keyPrefix = `${process.env.NEXT_PUBLIC_APP_ENV}-${buildId}:`;
    
    if (!client.isOpen || !client.isReady) {
      await client.connect();
    }
    
    redisCache = await createRedisCache({
      client,
      useTtl,
      keyPrefix,
      timeoutMs: 5000,
    });
  } catch (error) {
    // If we encounter an error with `client.connect()`, then `redisCache` will be undefined
    // and will be skipped as a cache handler, defaulting to the local LRU cache
    console.error('Redis connection error:', error.message);
  }
}
```

**Comment by MauriceArikoglu** [comment]
> I'm also seeing the same error with a Kubernetes deployment. ...
> 
> ```js
> // Skip Redis connection during builds
> if (process.env.REDIS_AVAILABLE && buildId) {
>   ...
> }
> ```

By the way, instead of checking REDIS_AVAILABLE injected config, we could also check for NEXT_PHASE, as system provided config value. `if (PHASE_PRODUCTION_BUILD !== process.env.NEXT_PHASE)` is true for build phase. 

-----
@better-salmon also something worth mentioning in the docs I believe. It's next specific but requires one less configuration to manage via environment.

**Comment by gtjamesa** [comment]
> By the way, instead of checking REDIS_AVAILABLE injected config, we could also check for NEXT_PHASE, as system provided config value. `if (PHASE_PRODUCTION_BUILD !== process.env.NEXT_PHASE)` is true for build phase. 

TIL, thanks!

**Comment by better-salmon** [comment]
Thank everyone for your help! After testing various setups, I can confirm that calling the `createClient` function at the top level during a build process can cause this error on some systems. I am currently working on improving the documentation. Additionally, I plan to revisit the section about [building without cache](https://caching-tools.github.io/next-shared-cache/configuration/opt-out-cache-on-build), but this will likely be in a separate pull request.

**Comment by better-salmon** [comment]
I have updated docs and example in vercel/next.js repo.
