### ISSUE TITLE
Can't get get/set functions to be called

### ISSUE THREAD

**Issue by wbern** [caching-tools/next-shared-cache#340]
**Brief Description of the Bug**
I don't know if this is a bug but I'm using nextjs in my nx project and no matter what I do, the set/get functions aren't called.

**Severity**
Major

**Frequency of Occurrence**
Always

**Steps to Reproduce**
I don't have a repro. I will happily close the issue if you think that's needed.

**Expected vs. Actual Behavior**
Running `pnpm nx build [app] --prod && pnpm nx serve [app] --prod` will start a prod instance of my nextjs server

I get the following output
```
HELLO CACHE HANDLER
using custom cache handler @neshca/cache-handler is not configured yet
 ○ Compiling /404 ...
 ✓ Compiled /404 in 6.7s (2799 modules)
using custom cache handler @neshca/cache-handler with 1 Handler and file system caching
using custom cache handler @neshca/cache-handler with 1 Handler and file system caching
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
using custom cache handler @neshca/cache-handler with 1 Handler and file system caching
 ○ Compiling /[market]/c/[campaignSlug] ...
 ✓ Compiled /[market]/c/[campaignSlug] in 8.3s (2943 modules)
using custom cache handler @neshca/cache-handler with 1 Handler and file system caching
using custom cache handler @neshca/cache-handler with 1 Handler and file system caching
using custom cache handler @neshca/cache-handler with 1 Handler and file system caching
```

But I expect to get my console log messages too.

This is my cache-handler.mjs file
```
import { IncrementalCache } from '@neshca/cache-handler';

console.warn('HELLO CACHE HANDLER');

IncrementalCache.onCreation(async () => {
  // Don't use Map in production. This is just an example.
  const cacheStore = new Map();

  const cache = {
    async get(key) {
      throw new Error('NOPE');
      console.warn('CACHE: GET', key);
      return cacheStore.get(key);
    },
    async set(key, value) {
      throw new Error('NOPE SET');

      console.warn('CACHE: SET', key, 'value:', value);

      cacheStore.set(key, value);
    },
  };

  return {
    cache,
    useFileSystem: true,
  };
});

export default IncrementalCache;

```

**Environment:**

- OS: [e.g., MacOS, Windows, Linux]
- Node.js version: 18.19.0
- `@neshca/cache-handler` version:  0.6.10
- `next` version: 14.1.0

**Dependencies and Versions**
List any relevant dependencies and their versions.
I'm using latest nx versions for nextjs.

**Attempted Solutions or Workarounds**
Describe any attempted solutions or workarounds and their outcomes.
I tried modifying these settings to set no memory size or to set some memory size.

  cacheHandler: require.resolve('./cache-handler.mjs'),
  cacheMaxMemorySize: 0, // disable default in-memory caching

**Impact of the Bug**
I'm not 100% if this is a bug or just me. I followed the troubleshooting steps but to no avail.

**Additional context**
I want to evict caches on my kubernetes cluster.

**Comment by better-salmon** [comment]
Hey @wbern! Do you see `console.warn('CACHE: GET', key)` and `console.warn('CACHE: SET', key, 'value:', value)` if you remove `throw` from `get` and `set`?

**Comment by wbern** [comment]
Hey!

I figured out that this was happening because the cache handler only runs in production mode, and for some reason my nx setup wasn't running next in production mode.

I'm gonna close this.

Would be nice to be able to test the cache handler without running a prod build.

Thanks!
