### ISSUE TITLE
404 when using `unstable_cache`

### ISSUE THREAD

**Issue by better-salmon** [caching-tools/next-shared-cache#391]
**Brief Description of the Bug**
Browser shows 404 page when using `unstable_cache` function.

**Severity**
Major (not Critical because `unstable_cache` is unstable)

**Frequency of Occurrence**
Always

**Steps to Reproduce**

1. Use the `unstable_cache` function on the page.
2. Open the page.
3. See 404 page instead of actual content.

**Expected vs. Actual Behavior**

Pages which are using `unstable_cache` must work.

**Environment:**

- OS: all supported OS
- Node.js version: all supported Node.js versions
- `@neshca/cache-handler` version: all above 1.0.0
- `next` version: all supported Next.js versions

**Attempted Solutions or Workarounds**
There is no workaround for now. CacheHandler doesn't read files from the file when using App Router. This was intentionally made. To overcome this bug, we must either read the file system or fix the unstable_cache function for Next.js. Reading the file system is a viable strategy only if we can identify if the page uses `unstable_cache`. As far as I know, it is not possible.

I also have a third idea: implement our `unstable_cache` function, which will allow Next.js to render a page if it was not read from the file system. It seems the easiest to me.

**Impact of the Bug**
`unstable_cache` is not working.

**Comment by pawelblaszczyk5** [comment]
I'm kind of suprised by this, because I've been using the `usntable_cache` with `@neshca/cache-handler` and `redis` just fine 😀 Is there some specific use case when it crashes that I'm unaware of?

**Comment by ezeparziale** [comment]
I tested all my functions with unstable_cache, and they work fine with Redis + Nextjs 14.1.3. I guess sometimes it doesn't work properly. But I still haven't made it productive.

**Comment by better-salmon** [comment]
@ezeparziale thank you for pointing out that you can not reproduce the issue. I've rerun the test and found out that the issue was in test case itself. I am closing the issue with the documentation update.
