### ISSUE TITLE
@neshca/cache-handler/redis-stack only deletes first ten entries associated with a tag

### ISSUE THREAD

**Issue by joshudev** [caching-tools/next-shared-cache#399]
**Brief Description of the Bug**
@neshca/cache-handler/redis-stack only deletes first ten entries associated with a tag.

**Severity**
Major

**Frequency of Occurrence**
Always

**Steps to Reproduce**
Use the redis-stack cache handler and call revalidateTag()

**Expected vs. Actual Behavior**
It should delete all the entries associated with the tag.

**Attempted Solutions or Workarounds**
For now I have created a custom handler which adds a high limit:

```
 const query = await client.ft.search(
        'idx:tags',
        `@tag:(${sanitizeTag(tag)})`,
        { LIMIT: { from: 0, size: 5000 } }
      )
```

**Comment by better-salmon** [comment]
@joshudev hello! I've made a PR with a fix. Thank you for opening this issue.
