### ISSUE TITLE
Don't discard stale while revalidate data at expiry time

### ISSUE THREAD

**Issue by m-sanders** [caching-tools/next-shared-cache#556]
**Brief Description of the Bug**

The Redis cache handler never returns stale responses and immediately evicts keys after the revalidate window expiry.

**Severity**

Major.

**Frequency of Occurrence**

Always

**Steps to Reproduce**

1. Using pages `getStaticProps` set `revalidate` to 1 second. Setup the Redis cache handler as described in Getting Started.
2. Build and run the application in production mode using the custom cache handler
3. Watch the keys in Redis using the CLI `watch 'redis-cli KEYS "*"'`
4. Visit the page to populate the cache.
5. Observe how after 1 second, the cache results are evicted.

**Expected vs. Actual Behavior**

I would expect the cache to behave similarly to the file system implementation. The cache returns stale entries after the freshness expiry to keep things responsive rather than immediately evicting stale keys at freshness expiry. Unlike the file system implementation, you would likely need to recommend a sensible key eviction policy along with allowing the configuration of a maximum stale expiry TTL for those who don't want to max out the memory on their Redis server.

**Environment:**

- OS: Mac OS
- Node.js version: v20.11.1
- `@neshca/cache-handler` version: 1.3.2
- `next` version: 14.2.3

**Comment by vermario** [comment]
I have observed the same thing and I have the same doubts that are expressed here...

**Comment by better-salmon** [comment]
Hello, @m-sanders and @vermario! You can achieve your goal by using the `defaultStaleAge` and the `estimateExpireAge` callback. Set the `defaultStaleAge` to one year and ensure that the `estimateExpireAge` callback returns one year as well. Doing this can prevent the cache entries from being evicted after the `revalidate` period.

Here is the docs about these parameters https://caching-tools.github.io/next-shared-cache/api-reference/ttl-parameters.

**Comment by grerealadvisor** [comment]
In fact it works if `estimateExpireAge` is bigger than `defaultStaleAge` or your revalidate duration.

**Comment by m-sanders** [comment]
Ah

> Hello, @m-sanders and @vermario! You can achieve your goal by using the `defaultStaleAge` and the `estimateExpireAge` callback. Set the `defaultStaleAge` to one year and ensure that the `estimateExpireAge` callback returns one year as well. Doing this can prevent the cache entries from being evicted after the `revalidate` period.
> 
> Here is the docs about these parameters https://caching-tools.github.io/next-shared-cache/api-reference/ttl-parameters.

Apologies! I missed this. I'll close the ticket.
