### ISSUE TITLE
Feedback for “Creating a Custom Handler”

### ISSUE THREAD

**Issue by mihalacherazvan** [caching-tools/next-shared-cache#586]
Hello! I think there is a bug in your documentation page for creating a custom cache handler. In the `get` method of this custom handler the `implicitTags` parameter is not destructured resulting in an error when the `combinedTags` Set is built and the `get` method always returns null. I've also looked at your own implementation of the redis-strings handler where the parameter is indeed destructured.

Thanks!

**Comment by better-salmon** [comment]
Hello @mihalacherazvan, thank you for pointing it out!
