### ISSUE TITLE
next.js example update

### ISSUE THREAD

**Issue by mauroaccornero** [caching-tools/next-shared-cache#620]
It's not a bug, I just want to notify that I'm trying to update the [Next.js  example](https://github.com/vercel/next.js/pull/67350)

The example required some refactors because it was based on an older version of next-shared-cache and it was not working as reported on this [related issue](https://github.com/vercel/next.js/issues/66812)

I tried my best to replicate [your example](https://caching-tools.github.io/next-shared-cache/redis). 

If you have any additional comments or feedback it would be appreciated.

Thanks for all your hard work.

**Comment by better-salmon** [comment]
Hello @mauroaccornero! You are absolutely right; the example definitely needs some work. I will make sure to address it soon.

**Comment by better-salmon** [comment]
Hey @mauroaccornero! Thank you for updating the example in the Next.js repo! I'm so glad the community helps me maintain the `@neshca/cache-handler`.

**Comment by better-salmon** [comment]
Hey @mauroaccornero! Thank you for updating the example in the Next.js repo! I'm so glad the community helps me maintain the `@neshca/cache-handler`.
