### ISSUE TITLE
Built-in redis-stack handler not working

### ISSUE THREAD

**Issue by TariqSaiyad** [caching-tools/next-shared-cache#704]
**Brief Description of the Bug**
I've set up my cache-handler exactly as per [https://caching-tools.github.io/next-shared-cache/redis](https://caching-tools.github.io/next-shared-cache/redis). I also have the next.js config set up to use this cache handler

I've got a redis instance running when the next.js app is building. However, I get some error logs on the next.js side (see below)

**Severity**
Major

**Frequency of Occurrence**
Always

**Screenshots/Logs**

I've enabled the `NEXT_PRIVATE_DEBUG_CACHE` and this is what I see when the app is built and running.

```
Handler "redis-stack" failed to get value for key "1d996aaeb4672800577e17571348f62802586641d739ff8ea6363a62f192d99f". [ErrorReply: ERR unknown command 'JSON.GET', with args beginning with: ':1d996aaeb4672800577e17571348f62802586641d739ff8ea6363a62f192d99f' ]

Failed to update prerender cache for /favicon.ico [ErrorReply: ERR unknown command 'JSON.SET', with args beginning with: ':/favicon.ico' '.' '{"lastModified":1724059865778,"lifespan":{"expireAge":31536000,"expireAt":1755595865,"lastModifiedAt":172405' ]

Failed to update prerender cache for 5d62563b8e91f854086e1d7af325695d52b1e0f4e9dccc801f104b5f6cd2c811 [ErrorReply: ERR unknown command 'JSON.SET', with args beginning with: ':5d62563b8e91f854086e1d7af325695d52b1e0f4e9dccc801f104b5f6cd2c811' '.' '{"lastModified":1724059863085,"lifespan":{"expireAge":90' ]

using custom cache handler @neshca/cache-handler with 1 Handler
```

**Environment:**

- OS: Linux
- Node.js version: v20.14.0
- `@neshca/cache-handler` version: 1.5.1
- `next` version: 14.2.4

**Dependencies and Versions**
- `redis` version: 4.7.0

**Comment by mauroaccornero** [comment]
@TariqSaiyad it's known that calling createClient() during the build can [cause issues](https://github.com/caching-tools/next-shared-cache/issues/284#issuecomment-1919145094)  maybe you can try to [skip the redis cache during the build](https://github.com/mauroaccornero/next.js/blob/77ffeebe4dbab42a8bdb58b8d9fd750da7d0be59/examples/cache-handler-redis/cache-handler.js#L11)

maybe you can check if the RedisJson module is installed with 

```
redis-cli info modules
```

I hope this will help

**Comment by better-salmon** [comment]
@mauroaccornero thanks for your response! I want to add that the `RediSearch` module must be installed as well.

**Comment by better-salmon** [comment]
@TariqSaiyad, hey there! I'm closing this issue because there hasn't been any activity. If you're still experiencing problems, please feel free to contact me.
