### ISSUE TITLE
onCreation is not called

### ISSUE THREAD

**Issue by cbou** [caching-tools/next-shared-cache#731]
**Brief Description of the Bug**
The function onCreation isn't called which result on this logs:

```
using custom cache handler @neshca/cache-handler is not configured yet
[CacheHandler] Instance created with provided context.
```

**Severity**
Major

**Frequency of Occurrence**
Sometimes

**Steps to Reproduce**

I'm still working on steps to reproduce since it only appears on my project but not on the example app.

**Expected vs. Actual Behavior**
The function onCreation isn't called so the custom cache isn't configured.
**Environment:**

- OS: MacOS
- Node.js version: 18
- `@neshca/cache-handler` version: 1.6.1
- `next` version: 14

Maybe someone already had the issue and found out how to solve it?

**Comment by JohnJasonFisher** [comment]
Hello, I'm having the same issue, did you fix the issue?

I followed the 
https://caching-tools.github.io/next-shared-cache/installation
instructions and then the 
https://caching-tools.github.io/next-shared-cache/redis
and added a .env file with NEXT_PRIVATE_DEBUG_CACHE=1.

When I start the app with `npm run build && npm run start`, I see 
```
using custom cache handler @neshca/cache-handler is not configured yet
[CacheHandler] Instance created with provided context.
```

and when I visit the page, I see no data in Redis.

I also added a console.log statement to my cache-handler.mjs file and I notice that the statement isn't logging, leading me to believe that onCreation is not being called.
