### ISSUE TITLE
Add docs for `diskAccessMode` field in `onCreation` callback

### ISSUE THREAD

**Issue by better-salmon** [caching-tools/next-shared-cache#98]
Explain in more detail how to configure access to the file system.

```js
IncrementalCache.onCreation(() => {
  return {
    diskAccessMode: "read-yes/write-yes”, // and others
  };
});
```

**Comment by itzsrikanth** [comment]
Hi @better-salmon, I was looking for way to contribute and found the procedure [here](https://github.com/caching-tools/next-shared-cache/issues/101#issuecomment-1826444020). Can I contribute to this doc at `docs/cache-handler-docs/src/pages/configuration/disk-access-mode.mdx` ?

**Comment by better-salmon** [comment]
Hey, @itzsrikanth! I appreciate your interest! You could try, but this topic is complicated. The whole purpose of the library is to make sharing the cache easy, and the `diskAccessMode` is almost the local thing.

`diskAccessMode` is crucial for the smooth functioning of the Pages router and acts as a backup option in case of a remote cache failure. However, some parts of `diskAccessMode` may become obsolete and may be removed before release.

Please create good documentation that's easy to follow! I'll be happy to review and provide feedback on your pull request.
